export const RU_DICT = {
  monthsNames: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
  event: "Событие",
  date: "Дата",
  time: "Время",
  show: "показать",
  error: "Ошибка файла",
  choose: "Выберите файл",
  chooseAnother: "Выберите другой файл",
  choosed: "Файл выбран",
  load: "Загрузить",
  uploaded: "Обновлено",
  minute3: "минуты",
  minute2: "минуту",
  minute1: "минут",
  seconds: "сек.",
  ago: "назад",
  newLiveData: "Новые данные!",
  empty:'Пока пусто<br>Обновите после первого вылета!',
  pilotsTab: {
    bestLap: "Лучший круг",
    round: "Раунд",
    heat: "Группа",
    start: "Старт",
    end: "Конец",
    time: "Время",
    bestConsecutive: `лучших круга`,
    average: "Среднее время круга",
    totalLaps: "Всего кругов",
    totalStarts: "Всего Стартов",
    allLaps: "Все круги",
    vs: "Добавить к сравнению",
  },
  leaderboardTab: {
    lap: "Круг",
    consecutive: `Круга`,
    totalLaps: "Всего кругов",
    average: "Среднее время",
    name: "Имя",
    round: "Раунд",
    time: "Время",
    starts: "Стартов",
    laps: "Кругов",
  },
  roundsTab: {
    heat: "Группа",
    round: "Раунд",
    view: "Просмотр",
    statistic: "Статистика",
    speed: "Скорость",
    play: "Старт",
    pause: "Пауза",
    again: "Начать заново",
    roundStart: "Начало раунда",
    name: "Имя пилота",
    laps: "Круги",
    bestLap: "Лучший круг",
    bestConsecutive: `3 лучшие круга`,
    totalTime: "Всего времени",
    holeShot: "Старт",
    lap: "Круг",
  },

  allLapsTab: {
    heat: "Группа",
    round: "Раунд",
    scale: "Масштаб",
    roundNum: "Номер раунда",
    lapNum: "Номер круга",
    lapStart: "Начало круга",
    lapEnd: "Конец круга",
    lapTime: "Время круга",
  },
  inRoundTab: {
    lap: "Круг",
    heat: "Группа",
    round: "Раунд",
    roundStart: "Начало раунда",
    lapNum: "Номер круга",
    lapStart: "Начало круга",
    lapEnd: "Конец круга",
    lapsNum: "Номера кругов",
    lapsStart: "Начало кругов",
    lapsEnd: "Конец кругов",
    lapTime: "Время круга",
    goToRound: "Перейти к раунду",
  },

  vsTab: {
    vs: "vs",
    laps: "Круги",
    statistic: "Статистика",
    heat: "Группа",
    round: "Раунд",
    scale: "Масштаб",
    roundNum: "Номер раунда",
    roundStart: "Старт Раунда",
    lapNum: "Номер круга",
    lapTime: "Время круга",
    bestLap: "Лучший круг",
    bestConsecutive: `лучших круга`,
    totalLaps: "Всего кругов",
    average: "Среднее время",
    starts: "Стартов",
    totalTime: "Всего времени",
  },
};

export const EN_DICT = {
  monthsNames: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
  event: "Event",
  date: "Date",
  time: "Time",
  show: "Show",
  error: "File error",
  choose: "Choose file",
  chooseAnother: "Choose another file",
  choosed: "File choosed",
  load: "Load",
  uploaded: "Updated",
  minute3: "minutes",
  minute2: "minutes",
  minute1: "minutes",
  seconds: "seconds",
  ago: "ago",
  newLiveData: "New Data!",
  empty:'Still Empty<br>Refresh page after first qual round',
  pilotsTab: {
    bestLap: "Best lap",
    round: "Round",
    heat: "Heat",
    start: "Start",
    end: "End",
    time: "Time",
    bestConsecutive: `Best consecutive`,
    average: "Average time",
    totalLaps: "Total laps",
    totalStarts: "Total starts",
    allLaps: "All laps",
    vs: "add to .Versus",
  },
  leaderboardTab: {
    lap: "Lap",
    consecutive: `Consecutive`,
    totalLaps: "Total laps",
    average: "Average",
    name: "Name",
    round: "Round",
    time: "Time",
    starts: "Starts",
    laps: "Laps",
  },
  roundsTab: {
    heat: "Heat",
    round: "Round",
    view: "View",
    statistic: "Statistic",
    speed: "Speed",
    play: "Start",
    pause: "Pause",
    again: "Again",
    roundStart: "Round start",
    name: "Pilot name",
    laps: "Laps",
    bestLap: "Best lap",
    bestConsecutive: `Best consecutive`,
    totalTime: "Total time",
    holeShot: "Hole shot",
    lap: "Lap",
  },

  allLapsTab: {
    heat: "Heat",
    round: "Round",
    scale: "Scale",
    roundNum: "Round",
    lapNum: "Lap number",
    lapStart: "Lap start",
    lapEnd: "Lap end",
    lapTime: "Lap time",
  },
  inRoundTab: {
    lap: "Lap",
    heat: "Heat",
    round: "Round",
    roundStart: "Round start",
    lapNum: "Lap number",
    lapStart: "Lap start",
    lapEnd: "Lap end",
    lapsNum: "Laps numbers",
    lapsStart: "Consecutive start",
    lapsEnd: "Consecutive end",
    lapTime: "Lap time",
    goToRound: "Go to round",
  },

  vsTab: {
    vs: "vs",
    laps: "Laps",
    statistic: "Statistic",
    heat: "Heat",
    round: "Round",
    scale: "Scale",
    roundNum: "Round",
    roundStart: "Round start",
    lapNum: "Lap number",
    lapTime: "Lap time",
    bestLap: "Best lap",
    bestConsecutive: `Best consecutive`,
    totalLaps: "Total laps",
    average: "Average",
    starts: "Starts",
    totalTime: "Total time",
  },
};

export const SPEED_NAMES = {
  3: 0.3,
  2: 0.5,
  1.1: 1,
  // '1': 2.5,
  1: 2,
};
export const SPEED_VALUES = [3, 2, 1.1, 1];
